### ISSUE TITLE
Handling legacy content

### ISSUE THREAD

**Issue by nilshoerrmann** [getkirby/editor#100]
We updated to the latest versions of Kirby and Editor yesterday and it seems like the field no longer handles existing content properly. We have Markdown in our content files that is displayed as is inside the Editor, inline formatting is not applied correctly:

<img width="920" alt="grafik" src="https://user-images.githubusercontent.com/25466/64604487-89c4c100-d3c2-11e9-8bf2-aa08f87f63c7.png">

There are no errors in the console but I get the orange save bar every time I load the page although there are no manual changes. Clicking revert has no effects.

We are on https://github.com/getkirby/kirby/commit/218224c1c88c3c3c6e628cc8d09cbfe0ce6df1f5 (latest `develop`) and Editor `master` branch at 57c2df672299d0cca99f0864f3484245fd506b8b. Using latest Firefox for macOS.

**Comment by nilshoerrmann** [comment]
Hitting save will store the content in the blocks format but still not apply any inline formatting:

```json
[
    {
        "attrs": [],
        "content": "[Pompodium](http://pompodium.de) ist ein Ensemble f\u00fcr das Open-Source-Redaktionssystem [Symphony](http://getsymphony.com). Das Projekt entstand f\u00fcr das Symphony-Symposium 2010 in London und ist seit Herbst 2013 auch f\u00fcr die neuste Symphony-Version verf\u00fcgbar. Das Paket steht [auf Github kostenlos zum Probieren](https://github.com/hananils/pompodium) zur Verf\u00fcgung. Eine [Lizenz](http://pompodium.de/licence/) kostet 25 Euro.",
        "id": "_nVm8PONlL",
        "type": "paragraph"
    }
]
```

**Comment by nilshoerrmann** [comment]
I also checked the content file before saving in the panel and it contained plain Markdown so this is definitely a misinterpretation of the Editor itself.

**Comment by nilshoerrmann** [comment]
Let me just point out the severity of this issue: this broke content editing and content output completely on a site we were updating to use Editor. Half the content was created with Editor directly (that part works) but all existing content can neither be edited nor be output correctly.

**Comment by bastianallgeier** [comment]
✅
