### ISSUE TITLE
YouTube/Video embed - invalid JSON due to escaping

### ISSUE THREAD

**Issue by GiantCrocodile** [getkirby/editor#103]
default template:
```
<?= $page->text()->html()->kirbytext() ?>
```

Blueprint:
```
title: editor test

fields:
  text:
    label: Editor
    type: editor
```

```
{
    "attrs":{
        "src":"https://www.youtube.com/watch?v=ORuLr1dDiKE&list=PLGWGc5dfbzn-HX1ejbEwa2l2xMMs_9iNe&index=59", "caption": ""
    },
    "content":"",
    "id":"_6i7kiq03d",
    "type":"video"
},
```

Validated via http://json.parser.online.fr/ and https://jsonformatter.curiousconcept.com/

I think the `"` at the end of the `src` URL is wrong due to html() escaping. Is this a bug? I'm not sure because I suspect it should only escape if necessary and always provide a valid JSON.

**Comment by bastianallgeier** [comment]
The validator only fails if you keep the trailing comma. That's not included in the full JSON though.
