### ISSUE TITLE
new editor shows "null" block

### ISSUE THREAD

**Issue by GiantCrocodile** [getkirby/editor#105]
When I create a page via blueprint the new editor shows the string `null` as the first block.

![grafik](https://user-images.githubusercontent.com/6271057/64997427-fb2fd280-d8e0-11e9-82db-8b9751c9cc7f.png)

This happens on latest Firefox with Kirby 3.2.4. No PHP errors or browser console errors logged.

**Comment by m-artin** [comment]
I can report the same issue here.

**Comment by bastianallgeier** [comment]
✅
