### ISSUE TITLE
Hide drag handle and dropdown arrow when block not selected

### ISSUE THREAD

**Issue by HYR** [getkirby/editor#106]
<img width="903" alt="image" src="https://user-images.githubusercontent.com/5200901/65075033-526e8b00-d953-11e9-9b85-6d6433d5c265.png">

Currently the drag handle and drop down button are visible in at least one block all of the time. It may be done this way to make it discoverable (I'm not sure). In the above image, none of the blocks are currently selected or in focus but the drag handle and the drop down button are still visible. This implied to me that all of the below content was in that block, but then you realize that it's not when you start using it and from that point onward it becomes visually distracting making me feel like I've got that block selected when I don't. I'd like to suggest that it behave more like notion's implementation and only be visible when you hover over a block.

**Comment by GiantCrocodile** [comment]
Furthermore there should be no drag and drop button if there's less or equal than 1 block.

**Comment by bastianallgeier** [comment]
✅
