### ISSUE TITLE
[Translation] "CSS-Selektor" / "CSS-Klasse"

### ISSUE THREAD

**Issue by nilshoerrmann** [getkirby/editor#107]
The German translation features the following term:

https://github.com/getkirby/editor/blob/24c62279c7bb64c14cc406cf3cdcce980de343da/i18n/de.php#L16

This is "CSS class" in English which makes more sense from an editor's perspective. This should be "CSS-Klasse" or just "Klasse" in German, too, in my eyes.

(If "Selektor" is here to stay, it should be interlinked with a dash: "CSS-Selektor".)

**Comment by bastianallgeier** [comment]
✅
