### ISSUE TITLE
Image block attributes

### ISSUE THREAD

**Issue by nilshoerrmann** [getkirby/editor#108]
I just noticed that the attribute of the image block is named `css`. This sounds misleading because the attribute doesn't include actual CSS. Instead is stores a CSS class name. So shouldn't this attribute be named `class`?

**Comment by bastianallgeier** [comment]
I used css to avoid issues with the reserved word `class` in PHP and JS.

**Comment by nilshoerrmann** [comment]
Interesting. Is that actually an issue when used inside a JSON structure?

**Comment by bastianallgeier** [comment]
I don't think so. As far as I know there are no reserved words in JSON.

**Comment by nilshoerrmann** [comment]
In this case, I'd still say the naming is wrong, at least weird.

**Comment by bastianallgeier** [comment]
If I can't use the name safely in JS and PHP, it doesn't make sense to store it like this in JSON.

**Comment by bastianallgeier** [comment]
The only alternative would be className, but to change this now would break all class names for those who already use the editor for their sites.

**Comment by nilshoerrmann** [comment]
`className` is way better in my eyes than `css`.

> The only alternative would be className, but to change this now would break all class names for those who already use the editor for their sites.

Yes, but this is pre-release software! Things are still in flux :)

Don't get me wrong, of course it works as it is. I just think the current naming is misleading. But while I understand your reasoning from the developer perspective, it's not that clear when you are coming from a templating perspective where we all are going to deal with it. Especially because we have a core helper method `css()` which – correctly – deals with creating `link` elements.

To me this does not make sense:

```
<p class="<?=$attrs->css()?>"></p>
```

While this does:

```
<p class="<?=$attrs->className()?>"></p>
```

And just to point out why I'm so annoying: When we started using Kirby, we were confronted with some illogical things that were the way they were due to "historical reasons". This is creating barriers for new users. I'm trying to highlight these issues while they are still present and not historical ;)

**Comment by lukasbestle** [comment]
@bastianallgeier Did you already try using `class` before for the Editor? Where did it break? In most cases there are ways to get around the reserved word issues.

**Comment by bastianallgeier** [comment]
@lukasbestle to be honest, I got burned by this a couple times already in other projects, so I didn't even try it this time. Normally, I end up reverting code eventually when I use class as a variable name somewhere. 

@nilshoerrmann I totally appreciate this kind of feedback! As you know there are only 2 major problems in programming: 

1. Naming things
2. Cache invalidation 
3. Off-by-one errors
