### ISSUE TITLE
Bug: Uploaded images are not visible before saving

### ISSUE THREAD

**Issue by medienbaecker** [getkirby/editor#111]
When uploading images directly to the editor field, they will not be visible in files sections. Only after you reload, revert or save the page they appear.

![2019-09-23 14-53-09 2019-09-23 14_54_55](https://user-images.githubusercontent.com/7975568/65427204-1d11e380-de12-11e9-974e-d5ef211a56ac.gif)

It's also not in sync the other way around. When deleting an image from the page, it will still be visible in the editor field.

**Comment by bastianallgeier** [comment]
✅
