### ISSUE TITLE
Can't include images

### ISSUE THREAD

**Issue by possible-is** [getkirby/editor#112]
I can't get images into the editor field. 
First, the image that was already included through kirbytext looks broken. 
When i try to select another image, it shows an empty list (my images are saved with the template: image). After cancelling i get the message "this.files.filter is not a function"
When i upload an image through the editor, it loads and can't find it afterwards (no image is actually uploaded to the folder).

![Bildschirmfoto 2019-09-25 um 12 33 24](https://user-images.githubusercontent.com/4059869/65593510-e8786600-df90-11e9-9abc-f8e26adc0991.png)
![Bildschirmfoto 2019-09-25 um 12 33 54](https://user-images.githubusercontent.com/4059869/65593513-e8786600-df90-11e9-8dd7-1dab8a790159.png)
![Bildschirmfoto 2019-09-25 um 12 34 14](https://user-images.githubusercontent.com/4059869/65593512-e8786600-df90-11e9-94cb-19a888ad4376.png)
![Bildschirmfoto 2019-09-25 um 12 34 31](https://user-images.githubusercontent.com/4059869/65593511-e8786600-df90-11e9-9dca-d82ee3f20cb3.png)

**Comment by anthonyivol** [comment]
Same problem, I can upload files the classic way, but can't with image block in editor, I get **"imagename.jpg not found"** or If I click select, it **shows an empty list** :

![image](https://user-images.githubusercontent.com/19983700/66124961-09226a80-e5e6-11e9-8cdc-c32e13085a32.png)

![image](https://user-images.githubusercontent.com/19983700/66124869-dd06e980-e5e5-11e9-88d1-40bfb902dfcf.png)

**Comment by possible-is** [comment]
Seems to be a Chrome Issue. If i try it in Firefox, it works allright.

**Comment by anthonyivol** [comment]
@possible-is, tried with Firefox unfortunately without success, same problem.
Tried also to clear all blocks content, then save, reload page, and just try with one image block, same problem.

**Comment by anthonyivol** [comment]
This is what I get on Chrome console : 

![image](https://user-images.githubusercontent.com/19983700/66316534-21f98b80-e918-11e9-8851-75057417843c.png)

And if I visit the given url, I get :
```
{"status":"error","route":"pages\/([a-zA-Z0-9\\.\\-_%= \\+\\@\\(\\)]+)\/fields\/([a-zA-Z0-9\\.\\-_%= \\+\\@\\(\\)]+)(?:\/(.*))?","exception":"Kirby\\Exception\\PermissionException","message":"Unauthenticated","key":"0","file":"kirby\/config\/api\/authentication.php","line":12,"details":[],"code":403}
```

**Comment by anthonyivol** [comment]
Well, I have updated Kirby via composer and replaced the content of site/plugins/editor with the editor-1.0.0-beta.1.zip content and it works

**Comment by lukasbestle** [comment]
@possible-is Does it work for you as well with the latest versions of Kirby and the editor?

**Comment by possible-is** [comment]
@lukasbestle I am using kirby 3.2.5, not sure which version of Editor, but not older than 12 days ago. It works fine in Firefox, and not at all in Chrome (Mac).

**Comment by anthonyivol** [comment]
> Well, I have updated Kirby via composer and replaced the content of site/plugins/editor with the editor-1.0.0-beta.1.zip content and it works

@possible-is actually I had commented to fast as this didn't solved the problem. I redid the operation,  get my old site version on my local computer, add the plugin and update kirby, and that didn't work again with both latest version.

I tried a fresh kirby 3 starter-kit and the beta.1.0 version of the plugin install and image include was possible.

Actually I was trying the plugin on an existing kirby site with an existing textarea field. 
So I think the problem was not about plugin/kirby version but more something about an existing configuration/content as the plugin include something to convert your textarea to editor field automatically. 

After fews save, go back, save,... it works...

**Comment by bastianallgeier** [comment]
This is solved on master.

**Comment by possible-is** [comment]
With the new master in Chrome it doesn't work at all. i get only: t.map is not a function

**Comment by bastianallgeier** [comment]
@possible-is I really don't understand what's happening here in your case. I can work with images without any problems :/ Do you have any additional plugins running?

**Comment by bastianallgeier** [comment]
I'm closing this now. After so many tests it must be something with a plugin.
