### ISSUE TITLE
$attrs: access to page and image?

### ISSUE THREAD

**Issue by mrflix** [getkirby/editor#113]
It's really cool that we can overwrite the editor snippets out of the box :)
My first step is to add srcset support to the image block.
So I need to access the image as a file object. Right now I'm doing this:

```php
$filename = str_replace($page->uid().'/', '', $attrs->id());
$image = $page->image($filename);
```

This doesn't feel good. Would it make sense to get direct access to the filename or even the file object?

And when I'm calling this from another `$page` it will break. So I was thinking that a `$attrs->page()` method could make sense here. Though `$attrs->image()` would make it unnecessary.

**Comment by bastianallgeier** [comment]
The image block offers access to the image object via the `$image` variable in the snippet. It can be null though if it's an external image and not one from Kirby.

**Comment by mrflix** [comment]
Awesome! I didn't know about that.

**Comment by yoanmalie** [comment]
Hi @bastianallgeier it's would be nice to note on the Wiki that we also have accesss to this `$image` variable because I didn't know it before' and think it's was imposible, until I find this issue.

Thanks!
