### ISSUE TITLE
Preserve newlines from pasted paragraphs

### ISSUE THREAD

**Issue by mrflix** [getkirby/editor#115]
When pasting one paragraph of text the editor nicely preserves the whitespace:

Pariatur ut velit nostrud 
deserunt excepteur irure 
sunt ut nisi 
cillum consectetur. 

![image](https://user-images.githubusercontent.com/60777/65804347-e6292e00-e181-11e9-9d24-11978467381a.png)

However when I paste in more than one paragraph, it loses its manners and just mushes everything together 🙊

Pariatur ut velit nostrud 
deserunt excepteur irure 
sunt ut nisi 
cillum consectetur. 

Laborum qui id laboris
id aliqua quis cupidatat
in ut dolor id do adipisicing

![image](https://user-images.githubusercontent.com/60777/65804361-f17c5980-e181-11e9-93bf-a86abf1ff980.png)

And it leaves an empty first row.

**Comment by bastianallgeier** [comment]
This is solved in the latest version on master.
