### ISSUE TITLE
Code Block dropdown obfuscated

### ISSUE THREAD

**Issue by adamkiss** [getkirby/editor#119]
When writing and `code` block is the last one, if you try to switch languages, last `X` rows are either invisible or obfuscated by the "<revert save>" toast. (`X` depends on conditions)

![CleanShot 2019-10-01 at 20 53 28](https://user-images.githubusercontent.com/481362/65991390-8f776900-e48d-11e9-816e-34e479f8515a.png)

Ideally, since selecting highlight language isn't possible without mouse, the flyout should show depending on screen position.

**Comment by bastianallgeier** [comment]
This will be fixed in 3.3.0. We already got a similar issue there which has been closed.
