### ISSUE TITLE
Weird copy and paste result

### ISSUE THREAD

**Issue by nilshoerrmann** [getkirby/editor#120]
I was pasting text – `(CET)` – inside an existing paragraph in the editor and it got added in this strange way:

<img width="932" alt="grafik" src="https://user-images.githubusercontent.com/25466/66039789-1a03ab00-e516-11e9-8f32-3b1727fe1a81.png">

I expected the text to be appearing at the visible cursor position (after "… German time").

The text was copied form Wikipedia, https://en.wikipedia.org/wiki/Central_European_Time – the forth word of the article. The underlying markup is `(<b>CET</b>)`.

**Comment by bastianallgeier** [comment]
✅
