### ISSUE TITLE
Cursor is not set correctly when combining blocks

### ISSUE THREAD

**Issue by medienbaecker** [getkirby/editor#123]
This is a tricky one to explain, so here's a gif where I only press backspace and enter repeatedly:

![editor-enter](https://user-images.githubusercontent.com/7975568/66465230-bed73880-ea80-11e9-89cd-50f69b81f7e5.gif)

Basically, the cursor is not set correctly when pressing backspace on a block to combine it with the previous one.

The content looks fine before butchering the content:
```
[
    {
        "attrs": [],
        "content": "Max Mustermann<br>Musterstra\u00dfe 1<br>12345 Musterhausen<br>Tel: 01234/5678",
        "id": "_j56t3bzso",
        "type": "paragraph"
    }
]
```

I'm using the latest Chrome and don't see any error message in the console.

**Comment by bastianallgeier** [comment]
I can't reproduce this. Can you please test with the latest version from master?

**Comment by medienbaecker** [comment]
I just tested it with the latest version from master and it's still exactly the same.
I don't understand why you can't reproduce it. It's a Kirby 3.2.5 installation, maybe that's the difference?

**Comment by bastianallgeier** [comment]
Ahhhh, it only happens when you have a line break in the paragraph before.

**Comment by bastianallgeier** [comment]
It looks like the line break is not counted when the length of the previous block is calculated. So it always results in the actual length - 1

**Comment by bastianallgeier** [comment]
✅  I found the issue and a fix for it :)
