### ISSUE TITLE
Loading legacy content with URL fails

### ISSUE THREAD

**Issue by nilshoerrmann** [getkirby/editor#127]
If the Editor finds legacy Markdown content it fails if plaintext links are present:

![Bildschirmfoto am 2019-10-11 um 12 23 39](https://user-images.githubusercontent.com/25466/66644741-ff21ec80-ec21-11e9-8a5f-4a0f20d5d166.png)

```
----

Description: Test

https://hananils.de

----
```

This does happen independend of any surrounding content as long as the URL is not marked up as link.

**Comment by bastianallgeier** [comment]
✅
