### ISSUE TITLE
Bug: Spaces removed while writing at the end of text

### ISSUE THREAD

**Issue by REHvision** [getkirby/editor#13]
![kirby-editor-alpha-bugs](https://user-images.githubusercontent.com/2584674/62223409-2acc5f00-b3b5-11e9-8803-e567d65fb38f.gif)

Kirby 3.2.2
Latest plugin version
Firefox 68

**Comment by bastianallgeier** [comment]
Urghs, seems to be a Firefox issue. I cannot reproduce it in Chrome, only in FF.

**Comment by bastianallgeier** [comment]
I just found a fix for it. It's on the master branch.

**Comment by REHvision** [comment]
Awesome :+1:
