### ISSUE TITLE
[Feature] Add `toField` method

### ISSUE THREAD

**Issue by nilshoerrmann** [getkirby/editor#133]
Because of the special content structure, the Editor doesn't allow for easy method chaining: calls like `$page->text()->blocks()->smartypants()` or `$page->text()->blocks()->excerpt(100)` won't work because we are inside a blocks collection.

It would be nice if the Editor offered a `toField` method which internally converts the current block collection to html, stores the result in `$field->value` and returns the current field instance. This would allow to chain methods as in the the above examples and also would allow more advanced manipulations like `$page->text()->blocks()->last()->toField()->excerpt(100)`.

**Comment by bastianallgeier** [comment]
✅
