### ISSUE TITLE
Bug: Pasting HTML into code block does not work

### ISSUE THREAD

**Issue by HashandSalt** [getkirby/editor#134]
Pasting an html snippet into the code block works on first save, but changing other parts of the page and saving again upsets the code blocks.

Original content store for the block:

```
"content": "  <div class=\"form-addon addon-right\">\n  <label>Newsletter Sign-Up</label>\n  <input class=\"input-text\" type=\"email\">\n  <button>Submit</button>\n  </div>",
```

Subsequent saves of the page strips the tags out of the pre formatted code block, and only leaves the plain text:

```
"content": "  \n  Newsletter Sign-Up\n  \n  Submit\n  ",
```

**Comment by bastianallgeier** [comment]
✅
