### ISSUE TITLE
Renaming `blocks()` to `toBlocks()`

### ISSUE THREAD

**Issue by nilshoerrmann** [getkirby/editor#135]
Looking at Kirby's naming scheme, it would be appropriate to rename the `blocks` method to `toBlocks`. On Slack, @texnixe explained the conventions as follows:

> [T]he method are classified as types: `states`, `converters` and `manipulators`. States start with is,  converters with to and manipulators have no prefix.

As the field converts a string of JSON to a blocks collection, the method classifies as converter. Sonja suggested naming the method `toBlocks` with an alias `blocks`.

**Comment by bastianallgeier** [comment]
✅
