### ISSUE TITLE
Usability: Editor options depending on context

### ISSUE THREAD

**Issue by romanustin** [getkirby/editor#139]
All suggestions and explanations in picture. Also I come to conclusion, that if user is on first empty line, or on new empty line, it's better to show (+) instead of (arrow down), as the only thing you can do on empty line is just to create content (so better change it to one click on (+) instead of (arrow down) and then "Insert below" or "Turn into"). So (arrow down) could be contextual. And also less options, that are not possible to use in case of empty line. If we change (arrow down) to (+) in case of empty line, then if we are on line with text, it's probably better to leave only arrow down with "duplicate" and "delete" options, and show (+) only when user goes to new line, as it's quite natural to expect to create new content from new line, but not from current.

![editor-context](https://user-images.githubusercontent.com/53936318/67719335-507bfb00-f9da-11e9-9dff-5d8ac86c3fc4.png)

**Comment by romanustin** [comment]
If you agree with this change, can offer solutions in more details, but for now the main point is that sometimes we have unneeded options, that can't be used, like "Delete" when there is nothing to delete, and another thing is that different options serve the same goal like "Insert below" or "Turn into" when I am on new emtpy line - they both would just create new content.

**Comment by HYR** [comment]
Personally, I disagree. I think all of the menu options _do apply_ even though haven't written any text yet because you have a text block created, you can convert it into a different type of block (again, even though it's empty of content). You can duplicate the block and delete it.

Perhaps the problem to solve is the context isn't clear. It's not clear that you have created a paragraph block vs any other type of block. What about adding placeholder text of "Paragraph" like the other blocks have (ex: Heading 1).

**Comment by bastianallgeier** [comment]
I agree with @HYR here. I have added the placeholder text to the paragraph block to fix this.

**Comment by romanustin** [comment]
Maybe I need to show more usage examples. Natural way of applying elements like H1 is normally pressing Enter, and then doing something with that line, or just going to not empty line, and then applying style (Turn into). Same as users would do in Word, or in other editors. So there is not much need in "Insert below", as it's easier just to press enter, and then convert new line to something else than standart text/paragraph. Now "Insert below" and "Turn into" are actually doing the same function, but are presented as two separate options. There is no need to have button for what is done with standart "Enter". Ok, it can be, when I am on the line with text, but on empty line "Insert below" is excessive. And still don't understand, why you think there is no point in contextual logic, like when it's empty line, why we need Delete or Copy option.

Placeholder "text" I think is excessive, as default is always text/paragraph. There are also usability studies, that show, that users often misunderstand placeholders and think they are actual text.

**Comment by romanustin** [comment]
Also might be better to remove "Turn into" option in some cases, like when I have image, now I can convert it to H2, and I can even turn it back to image, that's so cool, but can't imagine that usage case.
