### ISSUE TITLE
Kirby Editor needs a way to fallback to previous content

### ISSUE THREAD

**Issue by HYR** [getkirby/editor#140]
The issue is… when replacing a field with the new `editor` new content is saved using the editor's json format but old content has not yet been updated. When displaying this content on the front-end you get an error because that content has not yet been saved with the new format. There should be some fallback that happens until the content other content has been saved using the new format.

To get around this issue I had to create a little helper function:
```php
function isJSON($json) {
    $result = json_decode($json);

    if (json_last_error() === JSON_ERROR_NONE) {
        return 1;
    }

    return 0;
}
```
And use the above in my template:
```php
<?= (isJSON($page->text()))? $page->text()->blocks() : $page->text()->kt() ?>
```

**Comment by bastianallgeier** [comment]
Are you using the latest version? Normally, the blocks field method should already take care of this.
