### ISSUE TITLE
Error `this.blocks[index] is undefined` when trying to forward delete a soft return

### ISSUE THREAD

**Issue by johannahoerrmann** [getkirby/editor#142]
I've come across an error in the editor when trying to _forward delete_ a _soft return_ on the first line of a text block.

To recreate:

- enter soft return as first line of text in a text block
- go on that line and press forward delete (on my keyboard, `fn`+ `backward delete`)
- error is thrown

What I would expect:

I would expect the editor to simply delete that line (this is what happens when forward deleting a soft return in the middle of a paragraph).

Screenshots:

<img width="227" alt="grafik" src="https://user-images.githubusercontent.com/149678/67763179-607df400-fa47-11e9-8b75-c1028315d25d.png">

<img width="376" alt="grafik" src="https://user-images.githubusercontent.com/149678/67763733-a8e9e180-fa48-11e9-9ef4-f9093c1b7d50.png">

Version: 

- Editor: latest `master`
- Kirby: 3.3.0-rc.3

**Comment by bastianallgeier** [comment]
✅
