### ISSUE TITLE
Does not work inside structure filed

### ISSUE THREAD

**Issue by mynameisfreedom** [getkirby/editor#143]
I havent find that anyone else brought this up, Editor doesnt work inside Structure Field.

**Comment by HYR** [comment]
Yeah, I'm having the same issue.

**Comment by bastianallgeier** [comment]
This will now work with the new `pretty: false` option

**Comment by mynameisfreedom** [comment]
Thank you!

**Comment by PatricB** [comment]
@bastianallgeier I think it would be good if the "pretty" option were disabled by default to make saving and reading as stable as possible.
