### ISSUE TITLE
Phantom unsaved changes

### ISSUE THREAD

**Issue by nilshoerrmann** [getkirby/editor#144]
Currently, when I visit a page in the panel that uses the Editor field, I always get an unsaved changes notification. Nothing has changed actually, but the field seems to render links differently:

**before:**

`"content": "Eine ausf\u00fchrliche Projektdarstellung findet sich auf den Webseiten von <a href=\"http://eckhartbauer.de/forschung/busch-dirks-projekt/\">Prof. Dr. Eckhart Bauer</a>, der f\u00fcr die Leitung des Projektes verantwortlich ist."`

**after:**

`"content": "Eine ausf\u00fchrliche Projektdarstellung findet sich auf den Webseiten von <a title=\"null\" href=\"http://eckhartbauer.de/forschung/busch-dirks-projekt/\">Prof. Dr. Eckhart Bauer</a>, der f\u00fcr die Leitung des Projektes verantwortlich ist."`

Please note the additional `title=\"null\"`. The content file on the server holds the object without a `title`, but the API response to the panel adds the `title` attribute. There are two surprising elements in this fact:

1. Why is that attribute added while providing the content to the panel at all?
2. Why is the title attribute appended with a non-value of `null`?

Additionally, another strange thing is that I'm not able to undo these changes, only the approve button works – but that might be related to something in the Kirby core.

**Comment by bastianallgeier** [comment]
✅
