### ISSUE TITLE
[Panel] Switching languages doesn't update displayed content

### ISSUE THREAD

**Issue by nilshoerrmann** [getkirby/editor#145]
**Describe the bug**  
Switching languages in the panel doesn't update the field value to the correct language. I see non-translatable fields grayed out, but the content sticks to the first displayed language. 

If I toggle languages multiple times, the panel starts to display the correct languages after the 5th/6th language change.

**To Reproduce**  
Switch languages.

**Expected behavior**  
The content should update immediatelly. 

**Kirby Version**  
Kirby 3.3.0 RC3

**Additional context**  
The only field with translated content is an Editor field in my case. Maybe that's related.

**Comment by bastianallgeier** [comment]
✅
