### ISSUE TITLE
Deselecting Editor focuses a multiselect in editor

### ISSUE THREAD

**Issue by luxuryluke** [getkirby/editor#149]
When deselecting the Editor by clicking outside of it in Panel, Safari puts focus on a different Field on the page, a Multiselect Field which I have above the Editor Field, and clicking the Tab button doesn't switch to a different input field so I'm not sure what's happening. I've double checked my blueprints for errors.
Also, as a result, the page scrolls all the way to the top where that Multiselect field is visible.

<img width="388" alt="image" src="https://user-images.githubusercontent.com/57873/68237160-76496700-ffbb-11e9-91a6-62f1864e6547.png">

**Comment by luxuryluke** [comment]
After some testing, I no longer think this is an issue with Editor.
I believe this is either a K3.3 issue, or something wrong in my code/templates/blueprints, etc.

**Comment by bastianallgeier** [comment]
It's an issue with the multiselect field. We have a fix for that.
