### ISSUE TITLE
Video block doesn't allow custom sizes/classes

### ISSUE THREAD

**Issue by luxuryluke** [getkirby/editor#150]
This may be a case for making my own version of the Video block, which I should try.
When I used the Video in the regular markdown textarea, I was able to add in attributes to the markdown that included classes, width, height, etc.
There's no way to do this now, and the videos on the page are no longer full width in my rendered page design.
<img width="794" alt="image" src="https://user-images.githubusercontent.com/57873/68237496-130c0480-ffbc-11e9-9839-fb2fbf33cd0a.png">

Honestly, I should be defining the iframe width in CSS, I suppose, but the other method was working just fine (adding in width, etc. in the video kirbytag within the textarea).

Of course the result of all of this that I need to fix this all across my site content.

**Comment by mynameisfreedom** [comment]
For the moment I added this CSS to work properly. 

```
figure iframe {
    width: 100%;
    min-height: 400px;
}
```

**Comment by bastianallgeier** [comment]
To be honest this is something I don't think that the editor should offer width and height attributes for the iframe. CSS based sizing is a far better solution. The custom css class feature is already planned for all blocks.
