### ISSUE TITLE
Conversion to Markdown unaware of links

### ISSUE THREAD

**Issue by nilshoerrmann** [getkirby/editor#152]
When exporting Editor content to Markdown, links are not properly converted and are kept as HTML inside the Markdown document. They should be converted to their Markdown or KirbyText representation.

Considering that there will be third-party blocks, it might be interesting to not convert each block individually but take the full resulting HTML of the field and convert it to Markdown using something like https://github.com/thephpleague/html-to-markdown.

**Comment by bastianallgeier** [comment]
✅
