### ISSUE TITLE
Context menu misses options after 'Open in the Panel'

### ISSUE THREAD

**Issue by GiantCrocodile** [getkirby/editor#155]
Steps to reproduce:
1. Insert an image in the editor
2. Choose 'Open in the Panel' in context menu of the image block
3. Navigate backwards in your browser
4. Open context menu again

Problem:
Context menu items missing. Hovering it again, after the first time, makes them appear again.

Before:
![grafik](https://user-images.githubusercontent.com/6271057/68349064-1ad2c280-00fc-11ea-84df-ebbab0db976a.png)

After:
![grafik](https://user-images.githubusercontent.com/6271057/68349100-39d15480-00fc-11ea-83b4-addf57e59ad5.png)

**Comment by bastianallgeier** [comment]
✅
