### ISSUE TITLE
Better error message for wrong file type on Import Content

### ISSUE THREAD

**Issue by GiantCrocodile** [getkirby/editor#156]
When you choose to import content and select a file which contains no markdown or raw text, you get this error:

`mb_eregi_replace() expects parameter 3 to be string, null given`

A better error handling should be added to hint the user to choose a compatible file type.

**Comment by bastianallgeier** [comment]
What kind of file did you upload?

**Comment by GiantCrocodile** [comment]
I think I did misclick and tried to import a zip or docx file @bastianallgeier. This should happen with any file which is not a raw text file.

**Comment by bastianallgeier** [comment]
Normally, the upload for such file types should already be blocked. I will double-check

**Comment by bastianallgeier** [comment]
I tried to replicate this again and couldn't.

**Comment by GiantCrocodile** [comment]
@bastianallgeier I just downloaded the developer branch and replaced the zips content with my current editor plugin directory content. Clicking on the three horizontal dots and selecting 'Import content' and choosing a .docx file gives an error:

`mb_eregi_replace() expects parameter 3 to be string, null given`

Tested with Kirby v3.3.6.
