### ISSUE TITLE
Add excerpt() function to editor

### ISSUE THREAD

**Issue by GiantCrocodile** [getkirby/editor#159]
I would like to convert this line easily from textarea to editor:
`$article->text()->html()->excerpt(300)`

Right now, it seems that excerpt() isn't supported. A workaround seems to be this:
https://forum.getkirby.com/t/excerpt-for-editor-field/15970

**Comment by nilshoerrmann** [comment]
You can do `$article->text()->toBlocks()->first()->toField()->excerpt(300)`.

**Comment by GiantCrocodile** [comment]
This would only work with 300 chars if the first block contains those 300 chars, not the first x blocks summed together, right @nilshoerrmann? I think the excerpt() method works with 300 chars however they are organized/structured (simply because it's just one field with no structure at all).

Edit: It might work out to do `$article->text()->blocks()->toField()->excerpt(300)` or something similar. I have to give it a try later on.

**Comment by nilshoerrmann** [comment]
> Edit: It might work out to do $article->text()->blocks()->toField()->excerpt(300) or something similar. I have to give it a try later on.

I think the method is not available on the full blocks collection, only on a single block. But I haven't checked.

**Comment by GiantCrocodile** [comment]
Works:
`$article->text()->blocks()->first()->toField()->excerpt(300)`

Not working:
`$article->text()->blocks()->toField()->excerpt(300)`

The `toField()` fails on blocks() and thus excerpt is called on `null`.

**Comment by nilshoerrmann** [comment]
That's what I thought. Should not be to difficult to have this available on the blocks collection as well.

**Comment by bastianallgeier** [comment]
✅  `$article->text()->blocks()->excerpt()` is now available.
