### ISSUE TITLE
Strange errors together with kirby-builder and missing quotes?

### ISSUE THREAD

**Issue by ToGe88** [getkirby/editor#160]
Somehow if you set the editor as part of a builder-fieldset it doesn't seem to work properly. The ->blocks() function just writes out the JSON and doesn't seem to parse it to HTML. And i noticed, that the quotes around type-key and value are not closing properly: 

![image](https://user-images.githubusercontent.com/8841530/68391866-cca7d880-0168-11ea-93a4-3cbf8d52570d.png)

**Comment by bastianallgeier** [comment]
To make the editor work within the builder, you need to switch off the pretty option: 

```
  editor: 
    type: editor
    pretty: false
```
