### ISSUE TITLE
Bug: 'Insert below' and 'Turn into' Always Work Relative to Block with Insertion Point

### ISSUE THREAD

**Issue by luxlogica** [getkirby/editor#165]
## Description
In an Editor field with multiple paragraphs, when the user selects 'Insert Below...' or 'Turn into...' from a block menu, the operation is performed relative to the block where the insertion point currently is - not the block where the menu was opened and selected.

## Steps to reproduce
1. In an Editor field, add several paragraphs of text.
2. Click somewhere on the first paragraph, to place your insertion point there.
3. Scroll to the last paragraph, and clicking on its block menu, select 'Insert below...' and select any block type (doesn't matter).

## What is expected
We expect the new block to be inserted below the block where the menu was activated - ie., below the last paragraph. 

## What actually happens
The new block is inserted below the FIRST paragraph instead - where the insertion point was.

## Versions
Kirby 3.3
Editor 1.0

**Comment by MathiasGmeiner** [comment]
@luxlogica in my case it's always the block with the cursor in it.
![Kapture 2019-11-13 at 11 01 21](https://user-images.githubusercontent.com/103595/68753237-f51a5180-0604-11ea-9ff4-add8eea9575a.gif)

**Comment by luxlogica** [comment]
@MathiasGmeiner I think we're saying the same thing, right? The block that changes is always the block with the blinking insertion point, not the block where you opened the menu.

**Comment by MathiasGmeiner** [comment]
@luxlogica oops, yes! I got the "insertion point" wrong. Nevermind...

**Comment by bastianallgeier** [comment]
✅ This was weirdly only a Safari issue. But it's fixed now on the develop branch.

**Comment by MathiasGmeiner** [comment]
@bastianallgeier and Firefox. But I will try the develop branch.
