### ISSUE TITLE
Insert Menu Appears Under "Unsaved Changes Bar"

### ISSUE THREAD

**Issue by neildaniels** [getkirby/editor#167]
If the "Unsaved Changes" bar is visible in the Panel and the Editor field is close to the bottom of the screen (without additional content to scroll) then the bottom of the "Insert Below" menu can become obstructed.

<img width="340" alt="Screen Shot 2019-11-12 at 4 13 54 PM" src="https://user-images.githubusercontent.com/417182/68721589-b6828980-0567-11ea-8697-2b962e9e131d.png">

Kirby 3.3.0
Editor 1.0.0

**Comment by bastianallgeier** [comment]
The save bar is on top, but you can scroll down to reveal the entire dropdown.

**Comment by neildaniels** [comment]
@bastianallgeier At least in Safari, you cannot scroll. Haven’t tried other browsers.
