### ISSUE TITLE
Block extension - Single file components error

### ISSUE THREAD

**Issue by json-derulo** [getkirby/editor#173]
I'm trying to implement a block extension in a single Vue component as described [here](https://github.com/getkirby/editor/wiki/Block-extensions#single-file-components).

Doing so, results in a runtime error in the panel: `Uncaught SyntaxError: Cannot use import statement outside a module`

The issue occurs in the following line:

```
import CustomBlock from "./components/CustomBlock.vue"
```

**Comment by bastianallgeier** [comment]
If you want to make use of single file components, you need a build process. You can use our pluginkit to get started with a simple build setup: https://github.com/getkirby/pluginkit/tree/4-panel
