### ISSUE TITLE
Block dropdown menu can offer the wrong options, depending on focus

### ISSUE THREAD

**Issue by brianliddell** [getkirby/editor#174]
A minor UI issue, but potentially confusing for newbies. At least, it confused me!

The dropdown menu for every block in the Editor window seems to offer options appropriate to the block currently in focus. So if the focus is on a text block, the dropdown on an image block doesn’t offer image settings etc — and vice-versa.

**Comment by bastianallgeier** [comment]
This is fixed in 1.0.1-rc.1 and will be released tomorrow.
