### ISSUE TITLE
Insert Menu Appears Under "Unsaved Changes Bar"

### ISSUE THREAD

**Issue by neildaniels** [getkirby/editor#182]
Reopening #167. Can confirm that this still happens in Safari, but does not in Chrome.

If the "Unsaved Changes" bar is visible in the Panel and the Editor field is close to the bottom of the screen (without additional content to scroll) then the bottom of the "Insert Below" menu can become obstructed.

<img width="340" alt="Screen Shot 2019-11-12 at 4 13 54 PM" src="https://user-images.githubusercontent.com/417182/68721589-b6828980-0567-11ea-8697-2b962e9e131d.png">

Kirby 3.3.1
Editor 1.0.1

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Safari
 - Version: 13.0.3 (15608.3.10.1.4)

**Comment by bastianallgeier** [comment]
I finally have a fix for this! ✅
