### ISSUE TITLE
HTML prevents image blocks from being created

### ISSUE THREAD

**Issue by LeBenLeBen** [getkirby/editor#186]
**Describe the bug**
If you convert an existing page from markdown to JSON or import Markdown that contain HTML in it, for some reasons image blocks (and maybe others) are skipped.

**To Reproduce**
1. Create a page that has an editor field
2. Download and unzip [files.zip](https://github.com/getkirby/editor/files/3974169/files.zip)
3. Import text.md with the "import content" feature
4. The `(image: …)` tag in the file is not created as a block

If you remove the HTML from the text.md file and import it again, you'll see that the image block is properly created.

**Expected behavior**
The editor should create the image block without caring about HTML being present in the page or not.

**Kirby Version**
3.3.2

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Firefox
 - Version: 71

**Comment by bastianallgeier** [comment]
✅
