### ISSUE TITLE
Specify File Template for Image Uploads

### ISSUE THREAD

**Issue by neildaniels** [getkirby/editor#187]
I would like to be able to specify that images uploaded via the Editor should have a specific type of file template. In particular, I want them to show up in an `Files` section that only uses `template: image`.

As of Editor 1.0.1, it seems like there's no way to specify that uploaded images should have any particular template. Thus, they don't appear in my "image" file section.

**Comment by fabianmichael** [comment]
If you want a temporary solution, until this is fixed, here is the code that I am using to give every file without a template the default template. Does not cover every possible edge-case, but at least it worked for my project:

```php
Kirby::plugin('my/plugin', [
    'hooks' => [
        'file.create:before' => function ($file, $upload) {
            if ($file->template() === null) {
                // Set default template for files, that
                // have no template.
                $file->update([
                    'template' => 'default',
                ]);
            }
        },
    ],
]);
```

**Comment by bastianallgeier** [comment]
You should be able to set the template with: 

```yml
uploads: 
  template: editor-file
```
