### ISSUE TITLE
Stores image path to media folder, broken after deploy

### ISSUE THREAD

**Issue by distantnative** [getkirby/editor#189]
Editor stores media folder paths for images.
However, when I deploy, the media folder does not get deployed and thus after deployment all images in blocks are broken.

Shouldn't the editor rather store the content path, so that the media files can be regenerated on the server?

**Comment by texnixe** [comment]
Interestingly, I found that deploying the site  didn't have any negative effect, while the Panel and frontend images in the editor break when changing the page slug.

**Comment by distantnative** [comment]
Thinking about it, maybe it was not the deployment but moving the page to a subfolder that broke the links.

**Comment by bastianallgeier** [comment]
Normally, the editor should still be able to find the right images. But I will double-check

**Comment by neildaniels** [comment]
This seems to have weird side effects if you duplicate a page (and copy files). The content blocks in the duplicated post refer to the files in the _original_ page, which I wouldn't expect.

**Comment by bastianallgeier** [comment]
✅
