### ISSUE TITLE
Rename "Turn into…" Action to "Change type…" or "Convert…"

### ISSUE THREAD

**Issue by neildaniels** [getkirby/editor#193]
As an English speaker, I don't think I've ever seen the phrase "Turn into" in a piece of software.

I would definitely expect this to be called "Change type…" or "Convert…".

**Comment by bastianallgeier** [comment]
Fun fact: this wording is 100% stolen from Notion. I'm all up for turning it into something else (pun intended 😂)

**Comment by bastianallgeier** [comment]
✅
