### ISSUE TITLE
Add alt and target tags to links within editor text block

### ISSUE THREAD

**Issue by smongey** [getkirby/editor#198]
![Screenshot 2020-01-29 11 30 06](https://user-images.githubusercontent.com/1285493/73353337-08939b00-428b-11ea-9de9-9ccf9b810277.png)

**Comment by bastianallgeier** [comment]
I get the wish to include the target attribute, but why alt for a link? Did you mean support for the title attribute?

**Comment by bastianallgeier** [comment]
There's already an issue for the target option: https://github.com/getkirby/editor/issues/40 I'll be closing this in favour of the previous issue.
