### ISSUE TITLE
Line break not working for custom paragraph

### ISSUE THREAD

**Issue by medienbaecker** [getkirby/editor#207]
**Describe the bug**
Using `Shift + Enter` to insert a line break seems to be hard-coded for the core paragraph block type.
When extending that block type like the Intro example, line breaks don't work. It seems similar to https://github.com/getkirby/editor/issues/190 but this issue was closed for some reason.

**To Reproduce**
Use the Intro example block type and try pressing `Shift + Enter`. Compare the result with the regular paragraph.

**Expected behavior**
Line breaks should be possible for all block types. Otherwise it renders custom paragraph blocks useless.

**Screenshots**
Here I use the Intro example and try pressing `Shift + Enter`:

![linebreaks](https://user-images.githubusercontent.com/7975568/74655471-b6a8ab80-518c-11ea-9a4c-6392ba0c0a41.gif)

**Kirby Version**
3.3.3

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome 80.0.3987.106

**Comment by medienbaecker** [comment]
Adding `breaks: true` to `index.js` enables the line breaks:

```js
editor.block("intro", {
  extends: "paragraph",
  label: "Intro",
  icon: "text",
  breaks: true
});
```

I found this by looking at the headline blocks. It should be added to the documentation/examples though.

**Comment by bastianallgeier** [comment]
✅
