### ISSUE TITLE
Filter blocks

### ISSUE THREAD

**Issue by nilshoerrmann** [getkirby/editor#21]
It would be nice to [filter blocks similar to collections](https://getkirby.com/docs/cookbook/content/filtering). Two types of filter seem to be interesting:

1. filtering by type and 
2. filtering by attribute

This would give us the possibility to find the first paragraph for instance and use it as excerpt:

    $page->text()->blocks()->filterBy('type', 'p')->first()->html()

**Comment by nilshoerrmann** [comment]
As per the example, filters like `first` or `nth` would also be nice-to-haves.

**Comment by bastianallgeier** [comment]
✅
