### ISSUE TITLE
Use JSON_UNESCAPED_UNICODE

### ISSUE THREAD

**Issue by yandodov** [getkirby/editor#219]
Currently, the editor saves Cyrillic characters escaped. For example, `тест` is saved like this:

```json
{
    "attrs": [],
    "content": "\u0442\u0435\u0441\u0442",
    "id": "_1tug3ip28",
    "type": "paragraph"
}
```

I changed this line:

https://github.com/getkirby/editor/blob/master/field.php#L86

...to this:

```php
return json_encode($value, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE);
```

...and it works as expected:

```
{
    "attrs": [],
    "content": "тест",
    "id": "_1tug3ip28",
    "type": "paragraph"
}
```

---

I think the editor should not escape Unicode characters to make text files smaller and to make them readable.

**Comment by bastianallgeier** [comment]
✅
