### ISSUE TITLE
Blocks content as plain text.

### ISSUE THREAD

**Issue by guidoferreyra** [getkirby/editor#221]
Maybe is already possible but I couldn’t find anything on the wiki. But It would be super handy to have a method or something for retriebe blocks info as plain text. For instance I have a page text field using editor and I want to use that text for head meta description so I need the text without any html tags.

Best!

**Comment by bastianallgeier** [comment]
You can get the content editor as plaintext by clicking on the "dots" menu and selecting export. This will export a Markdown version for you.
