### ISSUE TITLE
Pasting text from Word inserts some kind of markup

### ISSUE THREAD

**Issue by moritzebeling** [getkirby/editor#227]
**Describe the bug**
When pasting text from Word, a strange line gets inserted as well:
```
schemas.microsoft.com/office/2004/12/omml”xmlns=”http://www.w3.org/TR/REC-html40“>
```

**To Reproduce**
1. Have some text in Microsoft Word and copy it to clipboard
2. Go to the Panel and paste the clipboard inside a text block of the Editor

**Expected behavior**
Well, it would be best, if this line wouldn’t appear ;)

**Screenshots**
Random Word document with various example formatting. But the problem occurs also without any formatting:
<img width="777" alt="Bildschirmfoto 2020-04-27 um 10 46 11" src="https://user-images.githubusercontent.com/39742729/80352534-51e88c00-8874-11ea-8ba4-b9ea6f3ebcc8.png">

When pasting the text in the Editor. Exact same result in Chrome and Safari:
<img width="692" alt="Bildschirmfoto 2020-04-27 um 10 38 40" src="https://user-images.githubusercontent.com/39742729/80352211-d4248080-8873-11ea-8403-79276f462857.png">

**Version**
Kirby 3.3.5
Editor 1.0.2

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Safari & Chrome

**Comment by bastianallgeier** [comment]
✅
