### ISSUE TITLE
A selection hit by ENTER doesn't delete selected text and doesn't create a new line

### ISSUE THREAD

**Issue by nimi09** [getkirby/editor#233]
**Describe the bug**
If you select a space character, or a word, and you press enter, the text doesn't get deleted, but instead a new Block gets created above

**To Reproduce**
Select some characters and press Enter

**Expected behavior**
By pressing Enter I expect the selection to be replaced with a new line, for the current Block. I don't expect a new Block.

**Editor Version**
1.0.2

(I am not sure if this is a bug or a feature request, but it's not the expected behavior )

**Comment by bastianallgeier** [comment]
✅
