### ISSUE TITLE
TypeError after deleting video block

### ISSUE THREAD

**Issue by moritzebeling** [getkirby/editor#239]
**Describe the bug**
When deleting a video block, something happens, that would’t let you open the block-menu of another block.

**To Reproduce**
1. Have an editor field containing at least two blocks, one (Vimeo) video and one other, e.g. text block.
2. Delete the video block using the arrow down button left to the video preview.
3. Now try to use the arrow down menu of the remaining block.
4. Once you click that, an error appears which leaves the user unable to continue editing.

**Screenshots**
Delete video block:
<img width="268" alt="Bildschirmfoto 2020-06-08 um 13 01 52" src="https://user-images.githubusercontent.com/39742729/84023584-a2c9c500-a988-11ea-9a95-16c2ffbbe77e.png">

Try to use other block menu:
<img width="166" alt="Bildschirmfoto 2020-06-08 um 13 02 20" src="https://user-images.githubusercontent.com/39742729/84023618-b2e1a480-a988-11ea-9b6f-8713444e2c1e.png">

Error appears:
<img width="533" alt="Bildschirmfoto 2020-06-08 um 13 03 02" src="https://user-images.githubusercontent.com/39742729/84023621-b4ab6800-a988-11ea-94f2-ffe3c2c6e620.png">

**Kirby Version**
Kirby 3.3.6
Editor 1.0.0

**Console output**
```
TypeError: undefined is not an object (evaluating 'this.$refs.settings.open')
  menu — index.js:1:236974
  menu
  (anonyme Funktion) — index.js:1:245020
  open — index.js:1:12143
  open
  mousedown — index.js:1:12932
  oe — vendor.js:41:11764
```

**Desktop (please complete the following information):**
macOS
Safari 13.1 + Chrome 83

**Comment by bastianallgeier** [comment]
I cannot reproduce this with the latest editor version. I believe this is already fixed. Please upgrade and feel free to reopen if it still happens.
