### ISSUE TITLE
Editor renders the same image for all images in the field

### ISSUE THREAD

**Issue by texnixe** [getkirby/editor#246]
**Describe the bug**
When an editor field has multiple images stored, the frontend renders the same image for all images in that field. Additionally, when adding new images and saving the page, the original filenames are replaced with the file that was added last. Happens with Editor 1.0.3.

**To Reproduce**
1. Replace Editor 1.0.2 with 1.0.3
2. Open a page with multiple images in frontend. All images are the same.
3. Add a new image in the Panel and save.
4. Check the content file: all filenames are now the same and reloading the page in the Panel will also show the same images.

**Expected behavior**
The filenames should not be changed and all images rendered correctly.

**Screenshots**

**Kirby Version**
Tested with Kirby 3.4 and Editor 1.0.3.

Forum post: https://forum.getkirby.com/t/issue-with-kirby-3-4-and-editor-rending-all-images-as-the-same-image/18751/2

**Comment by afbora** [comment]
Related PR about issue https://github.com/getkirby/editor/pull/240

**Comment by afbora** [comment]
@bastianallgeier Done

**Comment by bastianallgeier** [comment]
✅
