### ISSUE TITLE
In inline code double hypen does not work, weird behavior afterwards

### ISSUE THREAD

**Issue by Adspectus** [getkirby/editor#255]
In a text block when rendering some part as inline code, a double hyphen like --option does not work. Both hyphens will be rendered as a dash. Moreover if you will work around this, afterwards any keystroke leads to erasing the character in front of the cursor and replacing it with a dash

Add a text block with some text, then mark something as code and start typing two hyphens after each other. See attached screen cast.

Expected is that in inline code, 2 hyphens are not getting rendered as dash since 2 hyphens are valid in code.

Screen cast attached.

Kirby 3.4.2

 - OS: Ubuntu 18.04
 - Browser: Firefox 79.0

![Peek 2020-08-25 16-16](https://user-images.githubusercontent.com/8707493/91186959-ea423080-e6ef-11ea-9e5f-4afc64380b33.gif)

**Comment by afbora** [comment]
Duplicated with https://github.com/getkirby/editor/issues/184
