### ISSUE TITLE
Unable to write after a sequence of two dash characters

### ISSUE THREAD

**Issue by yandodov** [getkirby/editor#256]
**Describe the bug**
If I have the following content:

>Praesent nonummy -- mi in odio. Quisque libero metus, condimentum nec, tempor a, commodo mollis, magna. Ut tincidunt tincidunt erat. Fusce pharetra convallis urna. Sed consequat, leo eget bibendum sodales, augue velit cursus nunc, quis gravida magna mi a libero.

I'd be unable to write anywhere after the `--` sequence. That's because Kirby converts two dashes to a long dash. It works while you're writing it, but not if you copy-paste some content that contains `--`. If that happens, you're unable to write.

**Here's a video where I display this bug:**
[kirby-editor-bug-video.zip](https://github.com/getkirby/editor/files/5136916/kirby-editor-bug-video.zip)

I think the best solution is to have Kirby check if the current position of the caret is in-between the sequence of dashes.

**Kirby Version**
3.4.2

**Comment by afbora** [comment]
Duplicated with https://github.com/getkirby/editor/issues/184
