### ISSUE TITLE
Add MD docs to available import formats

### ISSUE THREAD

**Issue by herrajon** [getkirby/editor#264]
Given that the editor allows for export in MD. How about then importing the sam file again?

**Comment by bastianallgeier** [comment]
That already works.

**Comment by herrajon** [comment]
No it does not. Mac/Safari.

It does when c/p into the Editor. But not when fetching the .MD file. .TXT files on the other hand do work.

**Comment by bastianallgeier** [comment]
This is super strange. Could be a Safari bug as it works well in Chrome.

**Comment by herrajon** [comment]
Yes it is. Like you said it works in Chrome but not in Safari. This is a problem with other software as well. Unsolved:

https://github.com/writeas/writefreely/issues/334

**Comment by bastianallgeier** [comment]
This sucks. I seriously don't know how we could solve this on our end or build a work-around for it.

**Comment by herrajon** [comment]
Well. This is a nice to have feature, not must have. The strange people that have the urge to change the default ending to .MD will just have to C/P their content into the editor.

This is definetly and obviously out of Kirby's scope.

There are only two 'good' options. 

1) To wait and monitor if this is fixed in coming Safari updates.
2) Contact the Safari dev team and iform them politely but firmly about the situation.

I shall do both. If there will be any progress I will inform you.

I see this as closed issue.

Have a good one.

-j
