### ISSUE TITLE
Feature: Add new

### ISSUE THREAD

**Issue by nilshoerrmann** [getkirby/editor#30]
When looking a empty editor field or even when looking at a field with existing content, it's not very clear how to add new blocks. The arrow icon looks like a toggle for the context menu of the existing block only so I would not expect to find the "insert new" options there.

It would be helpful to have an empty line at the very bottom of the editor with – let's say – a plug icon or so that indicates to the users that they can add more blocks.

**Comment by nilshoerrmann** [comment]
A placeholder text might also be adaquat here (I know they are controversial, but it would really make sense here).

**Comment by mrflix** [comment]
I have the same problem. I'm quite confused about the end here:

![image](https://user-images.githubusercontent.com/60777/64189979-ab2f2580-ce75-11e9-8867-c96ed58da4ef.png)

I would expect a plus button with a list of possible blocks appearing once I click onto it.

**Comment by bastianallgeier** [comment]
✅

**Comment by piaaaac** [comment]
Is it possible to have the extended block list:

![image](https://user-images.githubusercontent.com/3965999/75382167-3e539000-58da-11ea-9a94-bb5d445d1b29.png)

replicated at the end of the editor? It would be really handy: now, especially when the last added block is very long, the user has to scroll back up to the beginning of the last block to add a new one. To not mess up the clean look of the editor it could appear on mouseover like this:

![animated](https://user-images.githubusercontent.com/3965999/75384377-4ca3ab00-58de-11ea-9494-5b700c635a0b.gif)

Thoughts?

**Comment by bastianallgeier** [comment]
@piaaaac I really like the dots! Maybe combined with a dropdown it would be even less intrusive. I like that direction.

**Comment by piaaaac** [comment]
The dropdown would be good if there are many blocks to choose from, but would require an additional click. While if there are just a few available blocks like in the example above the mouseover could make the experience smoother.

Maybe it could be a setting? Or we could think about something like this:

![frame-4 copy](https://user-images.githubusercontent.com/3965999/75769260-2a7ab480-5d46-11ea-9860-d731dc0ae574.png)

with the first two showing the most used ones.
