### ISSUE TITLE
Enhancement: Naming inconsistencies

### ISSUE THREAD

**Issue by nilshoerrmann** [getkirby/editor#33]
There are a few naming inconsistencies across the plugin:

1. It‘s `paragraph` and `image` not `p` and `img` but it‘s `h1` and `ol` and not `heading1` and `orderedlist`. As this is nothing the authors will ever see, I'd opt for the short html notation developers are familiar with.
2. It's `paragraph` in the configuration but in the interface it's just "text". As one block is always one single paragraph that name makes more sense to me than "text" that could actually be anything else, too, like headings, lists and so on.

**Comment by bastianallgeier** [comment]
I think I prefer the longer version that corresponds with the actual block labels.

**Comment by nilshoerrmann** [comment]
That's fine :) Consistency is the essistential thing.

**Comment by bastianallgeier** [comment]
I decided to keep it like it is. There are too many changes involved and no way is completely without inconsistencies.
