### ISSUE TITLE
Enhancement: UI alignment in the image block

### ISSUE THREAD

**Issue by nilshoerrmann** [getkirby/editor#36]
The alignment of the image block is strange: the UI elements and the button text is not on the same baseline. The space between the buttons looks off due to the italic "or" (is this needed at all?).

![grafik](https://user-images.githubusercontent.com/25466/62529043-28975400-b83e-11e9-8719-9fce15c5c387.png)

**Comment by bastianallgeier** [comment]
I split this in two.

**Comment by bastianallgeier** [comment]
✅
