### ISSUE TITLE
Enhancement: Accessing context actions

### ISSUE THREAD

**Issue by nilshoerrmann** [getkirby/editor#37]
When trying to reorder blocks, I have to focus the one I'd like to move. I'd expect this to work on hover already (click is fine for mobile, but it's unexpected on desktop).

Same is true for accessing the context menu.

**Comment by bastianallgeier** [comment]
Yes, this feedback has also come up from other sides. I will switch to hover soon.

**Comment by bastianallgeier** [comment]
✅
