### ISSUE TITLE
Feature: remove max-width of the blocks section  

### ISSUE THREAD

**Issue by bastianallgeier** [getkirby/editor#41]
Originally posted by @nilshoerrmann: 

> In the context of other fields, it's not clear why there is so much space left and right of the actual content blocks. My guess is that this should make sure we don't get too long lines and have a better readability. But in general this looks strange: so why not keep the padding as in the smallest breakpoint.

**Comment by bastianallgeier** [comment]
Without the max width of the blocks section it gets terribly messy to embed bigger images and also long lines are a big issue as you said. In my opinion, the field is to be seen separately from the other fields – a bit like the structure field. 

You also have the chance to adjust this in a custom css if you don't like it. That's why I'm closing it.

**Comment by nilshoerrmann** [comment]
The most irritating thing is the left padding. Why don't have max-width settings on a per block base? I understand that images should not be full width but that might not be true for other blocks.
