### ISSUE TITLE
Enhancement: Delete block

### ISSUE THREAD

**Issue by nilshoerrmann** [getkirby/editor#43]
As with adding new blocks, deleting blocks is not an obvious action because it's hidden in the context menu. This will not be an issue for advanced users but new users will be lost at first. Either having a delete icon on the right or having the three dot icon known from section will help.

This has also been mentioned on Slack.

**Comment by nilshoerrmann** [comment]
Maybe moving the delete option out of the arrow context menu to the right inside a three dot context menu will also minimize accidental deletions.

**Comment by luxlogica** [comment]
Would it be possible to have an "ⅹ" or "🗑" symbol that appears next to the block on hover only?

**Comment by iskrisis** [comment]
In my opinion this is sufficient and actually very well designed. Since the arrow is the main (and only) way to work with block (besides dragging) it makes most sense and its highly extensible (for different types blocks for example).

**Comment by romanustin** [comment]
> In my opinion this is sufficient and actually very well designed. Since the arrow is the main (and only) way to work with block (besides dragging) it makes most sense and its highly extensible (for different types blocks for example).

Also didn't see a problem in that, still, it's now hard to delete **all** content, when there are many `<p>` or `<li>`, CTRL+A will select only one element, so if I want to erase entire content of editor, it takes some time. So a button "Erase all" or some other solution could help.

**Comment by bastianallgeier** [comment]
I will close this. The dropdown is the way that we decided to go and additional buttons will clutter the editor quite a lot with many blocks. 

@romanustin you are definitely right that deleting multiple blogs is annoying, but this is related to the selection feature that we are planning.
