### ISSUE TITLE
Feature: Programmatically add, remove and alter blocks

### ISSUE THREAD

**Issue by nilshoerrmann** [getkirby/editor#46]
It would be nice to have an api to programmatically adjust blocks:

- appending or prepending blocks,
- removing blocks,
- altering blocks (attributes, content, type)

**Comment by nilshoerrmann** [comment]
Just to explain what this might be useful for: 

If you'd like to automatically add classes to blocks or adjust the headline hierarchy based on the page context, it might be easier to do this inside the controller and not to do complex logic in the templates or snippets.

**Comment by bastianallgeier** [comment]
You can already use the blocks collection to do this and to modify blocks based on what you want to do.

**Comment by nilshoerrmann** [comment]
Ah, cool! 

Given a blocks collection and I selected the third block, how would I prepend a block before that block? I cannot find examples how to do this with collections.

**Comment by nilshoerrmann** [comment]
E. g. something along this: 

```php
$page->text()->blocks()->nth(4)->prepend([
  'content' => $content, 
  'attr' => $attr
])
```

**Comment by distantnative** [comment]
Untested but as rough thought experiment:

```php
$before = $page->text()->blocks()->slice(0, 4);
$after = $page->text()->blocks()->slice(4);
$block = $page->text()->blocks()->nth(4);
$page->text()->blocks()->data([
  // block you would like to prepend,
  $block,
  // block you want to append
]);
$page->text()->blocks()->prepend($before);
$page->text()->blocks()->append($after);
```

**Comment by nilshoerrmann** [comment]
Okay, that looks quite complicated. Would it be possible to add methods for this, like `insertBefore`/`before` or `insertAfter`/`after`?
