### ISSUE TITLE
A version without Kirby as dependency

### ISSUE THREAD

**Issue by jenstornell** [getkirby/editor#57]
After what I've seen, this is brilliant!

I really want to see a version without Kirby as dependency as well. It could draw attention to Kirby. Let's say someone implement it into a competitor CMS for example and it has a link to Kirby CMS. It's a great free way to promote your product, especially as Kirby is still quite unknown.

**Questions around it:**

1. Is a version without Kirby as dependency a good idea? Why / why not?
1. If you don't think it's a good idea, will this repo remain MIT?
    In that case someone can in theory extract the editor to a Vue component, or something like that.

**Comment by bastianallgeier** [comment]
I thought about this, but it's probably nothing we want to focus on. The effort to keep a separate version is huge. We can't rely on our own component system, we have to make sure it works decoupled from our API and many other downsides are involved as well. We already tried that with our component system, but in the end we have to be pragmatic as a small team and focus on what's best for Kirby – not some potential competitors :)
