### ISSUE TITLE
Enhancement: Heading level setting in blocks() method

### ISSUE THREAD

**Issue by yandodov** [getkirby/editor#59]
Currently, the heading level is set in the `config.php`. It's OK to have that global option, but I feel like this belongs more in the blueprint. You're going to want different heading levels depending on where you use the editor.

For example, in the _default.yml_, I would want headings to start at level 2 since I want the _title_ field to be level 1. In another blueprint, however, I might have a subtitle that exists as its own field and it should be level 2, so the editor headings should start at level 3, instead of 2.

**Comment by bastianallgeier** [comment]
I think you are right that we need specific control for this, but it shouldn't be in the blueprint. This would mean that the blueprint needs to be loaded and parsed in order to render the template and that's not good. I would suggest something like this: 

```php
<?= $page->text()->blocks([
  'headingLevel' => 2
]); ?>
```

**Comment by yandodov** [comment]
I looked at the source and tossing the blueprint in there would indeed be bad. I like what you propose - it clearly splits configurations. You use the blueprint to configure the editor behavior in the panel, you use the template to configure the rendered markup.

I think you should have global settings in your `config.php` and merge them with whatever you provide to `blocks()`.

**Comment by bastianallgeier** [comment]
Yes, definitely. The options passed to the blocks method would overwrite the global config.

**Comment by nilshoerrmann** [comment]
Why not `$page->text()->blocks()->level(2)->html()`?

**Comment by bastianallgeier** [comment]
I think there will be more options in the future and the array seems to be more practical than having a setter for every option.

**Comment by bastianallgeier** [comment]
✅
