### ISSUE TITLE
Feature: Adding Underline Marking

### ISSUE THREAD

**Issue by ghost** [getkirby/editor#62]
Hello – I would love to underline the selected text. I've looked inside the plugins folder and saw, that there is already (besides bold, italic, etc) a underline option.
<img width="169" alt="Bildschirmfoto 2019-08-10 um 15 08 01" src="https://user-images.githubusercontent.com/39267327/62822211-a762f880-bb80-11e9-994e-d4a3e4a1e436.png">
I wonder, how I could activate it?
Thanks

**Comment by bastianallgeier** [comment]
TBH the underline and strikethrough styles are just not there yet, because Kirby doesn't have icons for those by default and I haven't implemented custom icons yet.

**Comment by bastianallgeier** [comment]
✅
