### ISSUE TITLE
Enhancement: formatting menu positioning

### ISSUE THREAD

**Issue by nilshoerrmann** [getkirby/editor#63]
With content wrapping inside a text block, the formatting menu position can be a bit weird:

<img width="925" alt="grafik" src="https://user-images.githubusercontent.com/25466/62859893-d8693780-bcfe-11e9-84e4-ba9414f07933.png">

In case it's not clear: I'm editing the link "auf Github kostenlos zum Probieren" here. 

I'm actually not sure where I'd expect the menu to be located but the current positioning is not logical to me. Maybe the menu should always be centered according to the first line of the selected content?

**Comment by nilshoerrmann** [comment]
Or maybe the positioning has to follow the line the user actually clicked on? Not sure if you actually _know_ about the lines.

**Comment by bastianallgeier** [comment]
I have to disagree with this. The menu shows on top of the first line to not overlap any part of the selection. It also always shows in the center of the selection to provide the shortest mouse paths. This behaviour is taken from TipTap and ProseMirror's own examples.

**Comment by nilshoerrmann** [comment]
I‘m fine with this as this is not the most important issue. But I still think the current solution is surprising while editing and looks broken. Let‘s see if this topic will come up again at a later time when the number of Editor users has grown.
