### ISSUE TITLE
Enhancement: Blocks collection

### ISSUE THREAD

**Issue by nilshoerrmann** [getkirby/editor#65]
When working with the blocks collection, it's possible to just echo the content of all blocks directly without calling the `html` method:

```php
<?=$page->text()->blocks() ?>
```

When filtering the collection, this throws an error though:

```php
<?=$page->text()->blocks()->first() ?>
```

> Object of class `Kirby\Editor\Block` could not be converted to string

It only works when using the `html` method:

```php
<?=$page->text()->blocks()->first()->html() ?>
```

I'd expect this to work without calling `html` in both situations.

**Comment by bastianallgeier** [comment]
✅
