### ISSUE TITLE
Bug: Does not work inside a Builder block

### ISSUE THREAD

**Issue by HashandSalt** [getkirby/editor#67]
Just gave this a go inside a builder block, and it seems to work until you press save, then the code that gets saved in the content file actually comes out in the panel! Not sure if the issue lies with the Editor plugin, or the fix involves changes to Builder.

![editor-issue](https://user-images.githubusercontent.com/28439755/62880670-d2d31800-bd25-11e9-8310-5225ef4af40a.jpg)

It also keeps thinking the page needs saving, but subsequent saves just make the issue worse....

![editor-issue-worse](https://user-images.githubusercontent.com/28439755/62880780-14fc5980-bd26-11e9-971d-f53579940f85.jpg)

**Comment by samnabi** [comment]
It does the same thing within a structure field.

**Comment by samnabi** [comment]
Notice how there is no closing quote after `"paragraph`

Something with the text saving is going wrong.

**Comment by HYR** [comment]
Since, at the moment, Kirby Editor doesn't support columns I'd very much like to see it compatible with the Kirby Builder and Structure fields to be able to work around that issue.

**Comment by thin-k-design** [comment]
I can confirm this behaviour.
I guess, I will have to wait for a stable release to use the amazing new editor.

By the way, also related: if I try to select an image in the editor in a kirby builder module I get the following error:
`Invalid file model type: kirby-builder/pages/{{currentPage}}/fields`

**Comment by bastianallgeier** [comment]
This will now work with the new `pretty: false` option

**Comment by Pechente** [comment]
> By the way, also related: if I try to select an image in the editor in a kirby builder module I get the following error:
> `Invalid file model type: kirby-builder/pages/{{currentPage}}/fields`

Did you find a fix for this yet? This error still pops up with 1.0.

**Comment by bastianallgeier** [comment]
@Pechente could you create a separate issue for that. I wasn't aware of that bug so far.

**Comment by thin-k-design** [comment]
@Pechente I didn't find a fix, but I still haven't tried the editor inside a kirby builder block after the update. I assumed it woud eventually fix this issue too. But as Bastian said open a new issue and link it here.

**Comment by findthebug** [comment]
open bug: https://github.com/getkirby/editor/issues/175

**Comment by favger** [comment]
Did someone solve this problem?

**Comment by Arnaud11** [comment]
add `|raw` after your attribute call (ex : `page.field|raw`)
