### ISSUE TITLE
Feature: Highlighting selected blocks

### ISSUE THREAD

**Issue by nilshoerrmann** [getkirby/editor#69]
When moving a page in a pages section, the selected item features a blue outline. It would be nice to have this for blocks as well because is not very visible which block is actually moved . There is a ghost element of the moved item but that actually visually clutters the view more than it helps understanding what is happening.

**Comment by bastianallgeier** [comment]
Related: #9
Related: #70

**Comment by bastianallgeier** [comment]
✅
