### ISSUE TITLE
Idea: Outsource examples

### ISSUE THREAD

**Issue by nilshoerrmann** [getkirby/editor#78]
It would be nice to have the examples outsourced into their own repositories. This way they can be installed and used. Furthermore, this will establish naming conventions for block extensions.

**Comment by DanielRivers** [comment]
I agree, all the examples are pretty good for usage in general

**Comment by bastianallgeier** [comment]
I think this is a good idea, but then I would start administrating those repos as well and accept issues and such. It just gets more complex and you could misunderstand those as official working plugins.

**Comment by nilshoerrmann** [comment]
What about providing the examples under your personal Github account and not inside the Kirby organisation?

**Comment by bastianallgeier** [comment]
I decided not to do this. Such repos are the box of the pandora.
