### ISSUE TITLE
Bug: Can't save an empty editor

### ISSUE THREAD

**Issue by yandodov** [getkirby/editor#80]
If I delete all content in the editor field (or not write any in the first place) and click Save, I expect to get an empty field, but instead I get:

```
Text:

[
    {
        "attrs": [],
        "content": "",
        "id": "_9ctdlppl3",
        "type": "paragraph"
    }
]
```

Thus, when I try `$page->text()->isEmpty()` in my template, I always get `false`.

I also think the editor should have some sort of view specific for empty content because this:

![image](https://user-images.githubusercontent.com/5570098/63154478-59834000-c019-11e9-9a17-d6c111999a21.png)

...is confusing. It's the first thing you see in a brand new page.

**Comment by nilshoerrmann** [comment]
Related to this: #35.

**Comment by romanustin** [comment]
> Thus, when I try $page->text()->isEmpty() in my template, I always get false.

Have the same problem, can't find a way to check if the field is empty.

**Comment by bastianallgeier** [comment]
It's a bit more difficult than I wished. For now you can wrap it in a count: 

```php
<?php if ($page->text()->blocks()->count()): ?>
<?= $page->text()->blocks() ?>
<?php endif ?>
```

Not ideal though. I'm working on a solution.

**Comment by yandodov** [comment]
@bastianallgeier just to be sure, I think the correct behavior at the end is to have a completely blank value, i.e. no JSON at all, when the field is empty.

**Comment by philipmarnef** [comment]
I'm getting a persistent 'unsaved changes' warning on empty fields, I suppose that's related or a known issue? I built from master, commit 454a36a.

**Comment by bastianallgeier** [comment]
✅
