### ISSUE TITLE
Feature: Handling legacy content

### ISSUE THREAD

**Issue by nilshoerrmann** [getkirby/editor#81]
When updating a textarea field to editor, everythings works fine inside the Panel as the plugin automatically updates the existing content to the new content model. But when working inside templates, using `$page->text()->blocks()` on a page that has not been updated yet in the Panel results in empty output.

I'd expect the editor to apply the same logic as for the Panel and convert old content on the fly.
Additionally, an option to update all content would be helpful to smooth transition.

**Comment by bastianallgeier** [comment]
✅
