### ISSUE TITLE
Feature: Interchangeable content models

### ISSUE THREAD

**Issue by nilshoerrmann** [getkirby/editor#82]
Because the Editor uses a very unique format to store content it would be helpful to have two opposite functions:

1. One to convert a field from basic Markdown/KirbyText input to the Editor content model.
2. Another to convert an Editor field back to Markdown/KirbyText.

This will make sure Editor is not a closed system that cannot be interchanged with another field. Having this flexibility to switch field types can be very important in more complex development processes where blueprints are in a constant state of flux.

_Related to #81._

**Comment by bastianallgeier** [comment]
So far the markdown import is happening in two phases. The backend converts markdown to HTML and sends that to the Editor. The Editor then uses an HTML parser to convert HTML to blocks. If this should be possible with PHP methods, it would all need to happen in the backend/PHP instead, which is a bit more complex. JS is quite good at parsing HTML docs, compared to PHP.

**Comment by nilshoerrmann** [comment]
I see. So if it's not possible to offer a bidirectional model, it would at least be necesssary to offer methods to convert the editor's block model to KirbyText/Markdown (blocks → HTML → Markdown?) because that is understood by other fields as well. Otherwise, we'd be locked into using editor.

**Comment by bastianallgeier** [comment]
I think I have a solution for this. I tested a few things in the last days and it looks like we can do all of the parsing on the server and then use that to convert the content in both ways. Looks very promising so far.

**Comment by bastianallgeier** [comment]
This is now possible in both ways.
