### ISSUE TITLE
Feature: Import Markdown document

### ISSUE THREAD

**Issue by nilshoerrmann** [getkirby/editor#85]
Although the editor offers a great visual interface it might be more convenient for authors to work in other apps to write their texts. For these users it would be helpful to offer a Markdown document importer either via the arrow menu or via drag & drop or via a button above the field.

**Comment by bastianallgeier** [comment]
That's the high-end stuff I would really love to have as well. Maybe even via copy + paste.

**Comment by bastianallgeier** [comment]
✅
