### ISSUE TITLE
Idea: "Disallowed" Block Types

### ISSUE THREAD

**Issue by mtclmn** [getkirby/editor#89]
Similar to how there is an 'allowed' block type option in the blueprint, it could be nice to also have a 'disallowed' or 'disabled' option in the blueprint.
If you only want to disabled 1 or 2 blocks types, would be nicer than defining all the blocks you _do_ want.

**Comment by bastianallgeier** [comment]
✅ The new disallowed option is now available. You can't mix allowed and disallowed though. You have to go for one of them.

**Comment by gagarine** [comment]
Documentation need an update https://github.com/getkirby/editor/wiki/Blueprint-setup#allowed

**Comment by bastianallgeier** [comment]
@gagarine I just added it to the docs.
