### ISSUE TITLE
Inspiration: Injecting new blocks

### ISSUE THREAD

**Issue by nilshoerrmann** [getkirby/editor#90]
I just saw this UI on ObservableHQ, https://observablehq.com/@mourner/martin-real-time-rtin-terrain-mesh, which makes adding new blocks very easy.

<img width="679" alt="grafik" src="https://user-images.githubusercontent.com/25466/63283233-fd3a4d80-c2b0-11e9-9148-168b7eb57324.png">

Each plus directly creates a new block at the given position. Might be an inspiration for Editor.

**Comment by mrflix** [comment]
Good idea!

I also like Tim's solution for the [kirby builder](https://github.com/TimOetting/kirby-builder):

![image](https://user-images.githubusercontent.com/60777/64190441-b040a480-ce76-11e9-9763-a3845e6aa251.png)

A gap between blocks and a dashed line that appears when you hover over the gap.

**Comment by bastianallgeier** [comment]
I'm going to close/archive this. Thanks for the inspiration!
