### ISSUE TITLE
Editor changed text of language locale field

### ISSUE THREAD

**Issue by romanustin** [getkirby/editor#91]
<img width="302" alt="Nustatymai | Tennis and More_2019-08-20_17-33" src="https://user-images.githubusercontent.com/53936318/63356651-d17e9c80-c370-11e9-90e4-fb9c87a83823.png">
Not sure if it's because of Editor, but looks like it changed field content (PHP locale string).

Also after I try to change it (to "lt" in this case), field is still being saved as "[object Object]"

Updated: problem was with Kirby version 3.1.3, with newest 3.2.3 works fine.

**Comment by bastianallgeier** [comment]
This is not related to the editor, but was a bug in earlier Kirby versions
