### ISSUE TITLE
Bug: allowed option not working independently for multiple editor fields

### ISSUE THREAD

**Issue by g5604** [getkirby/editor#94]
If i have more than one editor field, the allowed options that are set in the last field apply to all of the editor fields.

**Comment by medienbaecker** [comment]
To add to this: since the `allowed` setting is set incorrectly, you can then completely destroy the editor field by using a block type that's not allowed. This will result in an empty field and a console message that reads `block component does not exist: XY`.

**Comment by bastianallgeier** [comment]
✅
