### ISSUE TITLE
add to packagist so i can use travis ci for my custom block

### ISSUE THREAD

**Issue by bnomei** [getkirby/editor#95]
currently i have to manually download the plugin to my test directory.

if you add the editor to packagist i could add it to my plugins dev requirements. this way i could write tests for my custom block which is extending your blocks class. only this way it will work with travis ci.

**Comment by bastianallgeier** [comment]
This is a duplicate of: https://github.com/getkirby/editor/issues/58

**Comment by bnomei** [comment]
indeed but i explain why i need it. :D
