### ISSUE TITLE
Absolute url stored for images

### ISSUE THREAD

**Issue by webravenz** [getkirby/editor#99]
Image block store absolute url of the file on page content (for example http://mysite.local/path/to/image)

It breaks images if you upload page content files from local to staging for example.

**Comment by mynameisfreedom** [comment]
Oh, noooo :-(
I am converting website to Kirby and used editor plugin for many articles...

**Comment by bastianallgeier** [comment]
@mynameisfreedom don't worry too much about it. As long as it's an image from within Kirby, we can still fix this afterwards.

**Comment by mynameisfreedom** [comment]
Great!

**Comment by bastianallgeier** [comment]
Images inside Kirby are now stored with their internal Kirby ID. Even if the absolute src gets stored, it will later be replaced by the right one, depending on the server.
